# =========================
# Forward Proxy (HTTP/HTTPS)
# =========================

http {
    resolver 9.9.9.9 8.8.8.8 valid=10s ipv6=off;

    proxy_connect;

    log_format proxy_main '$remote_addr [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          '"$http_user_agent" '
                          'upstream_addr=$upstream_addr '
                          'upstream_status=$upstream_status '
                          'upstream_response_time=$upstream_response_time';

    access_log /var/log/nginx/proxy_access.log proxy_main buffer=16k flush=5s;
    error_log  /var/log/nginx/proxy_error.log warn;

    proxy_connect_timeout 10s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;

    proxy_buffering on;
    proxy_buffers 16 16k;
    proxy_buffer_size 32k;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";

    include /etc/nginx/conf-enabled/egress/http.d/*.conf;
}
