server {
    listen 3128;

    proxy_connect;

    # Permitir apenas domínios específicos
    if ($connect_host !~* ^(google\.com|github\.com|meusite\.com)$) {
    return 403;
    }

    location / {
        proxy_pass $scheme://$host$request_uri;
    }
}
