map $ssl_preread_server_name $target {
    example.com      10.10.10.20:443;
    api.example.com  10.10.10.21:443;
    default          10.10.10.30:443;
}

server {
    listen 443;
    ssl_preread on;
    proxy_pass $target;
}
